### ISSUE TITLE
Can I use muxy on Fargate containers

### ISSUE THREAD

**Issue by balajipothula** [mefellows/muxy#24]
How can I use muxy on Fargate containers?
Do I have to setup a packet dealy server?

**Comment by mefellows** [comment]
Sorry I missed this. I've never tried it on Fargate, but I imagine you could. As long as you can run a docker container with this you could start it.

One challenge for network shaping is that I think you'd need the `--all` linux capability, which I'm fairly confident would not be available on Fargate, so I think that wouldn't work.
