### ISSUE TITLE
Addition of hacktoberfest topic to the project

### ISSUE THREAD

**Issue by kishaningithub** [mefellows/muxy#27]
I feel adding the hacktoberfest topic to the list of labels in the project would greatly increase the visibility of this awesome project in my opinion

More info on hacktoberfest: https://hacktoberfest.digitalocean.com/

## Current topics
<img width="401" alt="Screenshot 2021-10-26 at 1 35 00 PM" src="https://user-images.githubusercontent.com/763760/138834850-907d9e40-497a-4e38-a4cd-0e35ea999e02.png">

**Comment by mefellows** [comment]
Done, thank you!

(I'm not sure the flood gates will open, but I'm staying positive 🤣)
